### ISSUE TITLE
Replace default Coder icon with FIGBERT logo

### ISSUE THREAD

**Issue by FIGBERT** [FIGBERT/figbert.com#1]
# Context
Since publishing [figbert.com](https://figbert.com/) to the public internet, the favicon has been a small version of the Coder logomark: ![favicon](https://user-images.githubusercontent.com/16868105/72703783-65fd4e80-3b0b-11ea-90ac-5503139dc6fb.png).
# Problem
The lack of a unique favicon shows laziness and a lack of attention to detail. The new favicon will enhance the brand image and spread the logo.
# Tasks
- [x] Find the FIGBERT logo svgs
- [x] Export the logo svgs into 16x16 and 32x32 favicon pngs
- [x] Substitute the new pngs for the previous favicons
