### ISSUE TITLE
Change codeblock syntax highlighting to brand colors

### ISSUE THREAD

**Issue by FIGBERT** [FIGBERT/figbert.com#2]
# Context
Codeblocks that are assigned a language with syntax highlighting support, like in the [Creating My Personal Site][1] post, are displayed on a black background with white and blue text.
# Problem
The syntax highlighting's blue-on-black stands out starkly from the rest of the site's purple-on-gray aesthetic. It disrupts the reader's flow and does not gel well with the brand's colors.
# Tasks
- [x] Find out how the syntax highlighting is provided
- [x] Change the code foreground color from blue to purple
- [x] Change the code background color from full black to a dark gray

[1]: https://figbert.com/posts/creating-my-personal-site/
